name: Running tests
on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.11
        uses: actions/setup-python@v2
        with:
          python-version: 3.11
      - name: Run tests
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install --only=dev
          poetry run nox
